### ISSUE TITLE
audio not playing on the server

### ISSUE THREAD

**Issue by ethanm22** [voice-cloning-app/Voice-Cloning-App#160]
hello
so I just got this working after I reinstalled all of my python stuff, everything works: I can load the server up and generate audio with it
but for some reason, when I go to play the audio, nothing plays: I checked the results folder after generateing the audio and it did generate something in their and that plays normaly
I'm stuck on this as when I used this last it worked, before doing the reinstall of my stuff
tryed reinstalling some dependencies and that didn't seem to fix anything
if someone could tell me what is going on here I would really appreciate it
I'm also running this in a virtual environment but don't think it has anything to do with that
thank you

**Comment by ethanm22** [comment]
another thing I just found out, is for some reason I am getting no progress updates on the server for things like training models and stuff: I can see them in the command line window, but they are not going on the server

**Comment by SirBitesalot** [comment]
What OS are you using? And which browser?
This sounds more like an issue with the browser if the results are generated and can play fine in an audio player,

**Comment by ethanm22** [comment]
hi
I'm using windows 10 and google chrome
I thaught it would have been the browser as well, but if I use the compiled release version everything works fine so I think it is an issue with my python setup or something

**Comment by Vidyut** [comment]
I just posted a change that needs to happen to the utils.py file https://github.com/BenAAndrew/Voice-Cloning-App/issues/166

I think this could be the same issue.
